server:
  address: 0.0.0.0
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/msf_customer}
    username: ${SPRING_DATASOURCE_USERNAME:msf_user}
    password: ${SPRING_DATASOURCE_PASSWORD:msf_password}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

